// src/backend/lib/swagger.ts
// OpenAPI spec for all Doodlpop API endpoints.

export const swaggerSpec = {
  openapi: "3.0.0",
  info: {
    title: "Doodlpop API",
    version: "1.0.0",
    description: "Backend API for the Doodlpop AI comic generator.",
  },
  tags: [
    { name: "Comic", description: "Comic creation and retrieval" },
    { name: "Script", description: "Script generation and approval" },
    { name: "Pages", description: "Page image generation" },
    { name: "Library", description: "Library and batch operations" },
  ],
  paths: {
    "/api/comic": {
      post: {
        tags: ["Comic"],
        summary: "Create a new comic",
        description: "Creates a comic and generates follow-up questions via Gemini.",
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                required: ["prompt", "artStyle", "pageCount"],
                properties: {
                  prompt: { type: "string", example: "A detective cat solves mysteries in a steampunk city" },
                  artStyle: {
                    type: "string",
                    enum: ["manga", "western_comic", "watercolor_storybook", "minimalist_flat", "vintage_newspaper", "custom"],
                    example: "manga",
                  },
                  customStylePrompt: { type: "string", nullable: true },
                  pageCount: { type: "integer", minimum: 1, maximum: 15, example: 5 },
                },
              },
            },
          },
        },
        responses: {
          "201": {
            description: "Comic created",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    comicId: { type: "string", example: "a1b2c3d4-..." },
                    followUpQuestions: {
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          id: { type: "string" },
                          question: { type: "string" },
                        },
                      },
                    },
                  },
                },
              },
            },
          },
          "400": { description: "Validation error" },
        },
      },
    },

    "/api/comic/random-idea": {
      get: {
        tags: ["Comic"],
        summary: "Generate a random comic idea",
        description: "Returns a random one-sentence comic premise generated by Gemini.",
        responses: {
          "200": {
            description: "Random idea",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    idea: { type: "string", example: "A retired astronaut opens a bakery on Mars." },
                  },
                },
              },
            },
          },
        },
      },
    },

    "/api/comic/batch": {
      post: {
        tags: ["Library"],
        summary: "Batch fetch comic summaries",
        description: "Fetches lightweight summaries for up to 50 comics by ID array.",
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                required: ["ids"],
                properties: {
                  ids: { type: "array", items: { type: "string" }, maxItems: 50 },
                },
              },
            },
          },
        },
        responses: {
          "200": {
            description: "Comic summaries",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    comics: {
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          id: { type: "string" },
                          status: { type: "string" },
                          title: { type: "string", nullable: true },
                          artStyle: { type: "string" },
                          pageCount: { type: "integer" },
                          thumbnailUrl: { type: "string", nullable: true },
                          createdAt: { type: "string" },
                          updatedAt: { type: "string" },
                        },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },

    "/api/comic/{id}": {
      get: {
        tags: ["Comic"],
        summary: "Get a comic by ID",
        description: "Returns the full comic object. Used for polling during generation and viewing.",
        parameters: [
          { name: "id", in: "path", required: true, schema: { type: "string" } },
        ],
        responses: {
          "200": {
            description: "Full comic object",
            content: {
              "application/json": {
                schema: { type: "object", properties: { comic: { type: "object" } } },
              },
            },
          },
          "404": { description: "Comic not found" },
        },
      },
    },

    "/api/comic/{id}/refine": {
      post: {
        tags: ["Comic"],
        summary: "Submit follow-up answers",
        description: "Saves answers to follow-up questions. All answers optional. Updates status to script_pending.",
        parameters: [
          { name: "id", in: "path", required: true, schema: { type: "string" } },
        ],
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                required: ["answers"],
                properties: {
                  answers: {
                    type: "object",
                    additionalProperties: { type: "string" },
                    example: { q1: "Inspector Whiskers — grumpy, wears a monocle" },
                  },
                },
              },
            },
          },
        },
        responses: {
          "200": { description: "Answers saved" },
          "404": { description: "Comic not found" },
          "409": { description: "Comic not in input status" },
        },
      },
    },

    "/api/comic/{id}/script/generate": {
      post: {
        tags: ["Script"],
        summary: "Generate the comic script",
        description: "Generates a full script via Gemini. Comic must be in script_pending status.",
        parameters: [
          { name: "id", in: "path", required: true, schema: { type: "string" } },
        ],
        responses: {
          "200": { description: "Script generated", content: { "application/json": { schema: { type: "object", properties: { script: { type: "object" } } } } } },
          "404": { description: "Comic not found" },
          "409": { description: "Comic not in script_pending status" },
        },
      },
    },

    "/api/comic/{id}/script/regenerate": {
      post: {
        tags: ["Script"],
        summary: "Regenerate script with feedback",
        description: "Regenerates the script incorporating user feedback. Comic must be in script_draft status.",
        parameters: [
          { name: "id", in: "path", required: true, schema: { type: "string" } },
        ],
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                required: ["feedback"],
                properties: {
                  feedback: { type: "string", example: "Make the villain more sympathetic" },
                },
              },
            },
          },
        },
        responses: {
          "200": { description: "Script regenerated" },
          "404": { description: "Comic not found" },
          "409": { description: "Comic not in script_draft status" },
        },
      },
    },

    "/api/comic/{id}/approve": {
      put: {
        tags: ["Script"],
        summary: "Approve script and set generation mode",
        description: "Approves the script and selects supervised or automated generation mode.",
        parameters: [
          { name: "id", in: "path", required: true, schema: { type: "string" } },
        ],
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                required: ["script", "generationMode"],
                properties: {
                  script: { type: "object" },
                  generationMode: { type: "string", enum: ["supervised", "automated"] },
                },
              },
            },
          },
        },
        responses: {
          "200": { description: "Script approved" },
          "404": { description: "Comic not found" },
          "409": { description: "Comic not in script_draft status" },
        },
      },
    },

    "/api/comic/{id}/generate-all": {
      post: {
        tags: ["Pages"],
        summary: "Generate all pages (automated mode)",
        description: "Generates all pages sequentially via Nano Banana Pro. Saves progress after each page. Long-running request.",
        parameters: [
          { name: "id", in: "path", required: true, schema: { type: "string" } },
        ],
        responses: {
          "200": { description: "All pages generated", content: { "application/json": { schema: { type: "object", properties: { comic: { type: "object" } } } } } },
          "404": { description: "Comic not found" },
          "409": { description: "Comic not in script_approved status or not in automated mode" },
        },
      },
    },

    "/api/comic/{id}/page/generate": {
      post: {
        tags: ["Pages"],
        summary: "Generate a single page (supervised mode)",
        description: "Generates the image for one page. Comic must be in supervised mode.",
        parameters: [
          { name: "id", in: "path", required: true, schema: { type: "string" } },
        ],
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                required: ["pageNumber"],
                properties: {
                  pageNumber: { type: "integer", example: 1 },
                },
              },
            },
          },
        },
        responses: {
          "200": { description: "Page generated", content: { "application/json": { schema: { type: "object", properties: { page: { type: "object" } } } } } },
          "404": { description: "Comic not found" },
          "409": { description: "Comic not in correct status or not in supervised mode" },
        },
      },
    },

    "/api/comic/{id}/page/regenerate": {
      post: {
        tags: ["Pages"],
        summary: "Regenerate a page (supervised mode)",
        description: "Regenerates a page, adding a new version. Maximum 3 regenerations (4 total versions).",
        parameters: [
          { name: "id", in: "path", required: true, schema: { type: "string" } },
        ],
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                required: ["pageNumber"],
                properties: {
                  pageNumber: { type: "integer", example: 1 },
                },
              },
            },
          },
        },
        responses: {
          "200": { description: "Page regenerated" },
          "400": { description: "Regeneration limit reached" },
          "404": { description: "Comic or page not found" },
        },
      },
    },

    "/api/comic/{id}/export/pdf": {
      get: {
        tags: ["Comic"],
        summary: "Export comic as PDF",
        description: "Generates and downloads a PDF of the completed comic. One page per PDF page. Comic must be in complete status.",
        parameters: [
          { name: "id", in: "path", required: true, schema: { type: "string" } },
        ],
        responses: {
          "200": {
            description: "PDF file download",
            content: { "application/pdf": { schema: { type: "string", format: "binary" } } },
          },
          "404": { description: "Comic not found" },
          "409": { description: "Comic is not complete yet" },
        },
      },
    },

    "/api/comic/{id}/page/select": {
      put: {
        tags: ["Pages"],
        summary: "Select a page version (supervised mode)",
        description: "Sets the selected version for a page. Marks comic complete if all pages are done.",
        parameters: [
          { name: "id", in: "path", required: true, schema: { type: "string" } },
        ],
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                required: ["pageNumber", "versionIndex"],
                properties: {
                  pageNumber: { type: "integer", example: 1 },
                  versionIndex: { type: "integer", example: 0 },
                },
              },
            },
          },
        },
        responses: {
          "200": { description: "Version selected" },
          "400": { description: "Invalid version index" },
          "404": { description: "Comic or page not found" },
        },
      },
    },
  },
};
